# Generated by Django 4.0.5 on 2022-07-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_number', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='rooms/images/')),
            ],
        ),
        migrations.DeleteModel(
            name='rooms',
        ),
    ]
